 
apiVersion: v1
kind: Service
metadata:
  name: pccomponentes-svc
  namespace: desarrollo
spec:
  ports:
  - name: tcp
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: pccomponentes-app